remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
skin: default
lang: en-US
title: Digital Innovation in Physiotherapy
subtitle: How Physiotherapy has changed over time?, New technologies , Overall Benefits
email: voramahek7@gmail.com
description: 
baseurl: # the optional subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name:
  twitter:
  picture:
twitter_username:
github_username: voram
logo: # path of site logo, e.g. "/assets/images/logo.png"
