remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
skin: default
lang: en-US
title: Digital Innovation in Physiotherapy
subtitle: How Physiotherapy has changed over time?, New technologies , Overall Benefits
email: voramahek7@gmail.com
github_username: voram
